const db = require('../db');

async function createReportsTable() {
  const sql = `
    CREATE TABLE IF NOT EXISTS reports (
      id INT AUTO_INCREMENT PRIMARY KEY,
      player_name VARCHAR(100) NOT NULL,
      player_surname VARCHAR(100) NOT NULL,
      year INT,
      club VARCHAR(150),
      team VARCHAR(150),
      laterality VARCHAR(5),
      contact VARCHAR(150),
      pos1 VARCHAR(10),
      pos2 VARCHAR(10),
      pos3 VARCHAR(10),
      pos4 VARCHAR(10),
      overall_rating DECIMAL(4,2),
      comments TEXT,
      tech_total DECIMAL(4,2),
      tact_total DECIMAL(4,2),
      phys_total DECIMAL(4,2),
      psych_total DECIMAL(4,2),
      pers_total DECIMAL(4,2),
      tech_cobertura_balon DECIMAL(4,2),
      tech_conduccion DECIMAL(4,2),
      tech_control DECIMAL(4,2),
      tech_regate DECIMAL(4,2),
      tech_disparo DECIMAL(4,2),
      tech_pase DECIMAL(4,2),
      tech_remate_cabeza DECIMAL(4,2),
      tech_anticipacion DECIMAL(4,2),
      tact_transicion_ataque_defensa DECIMAL(4,2),
      tact_movimientos_sin_balon DECIMAL(4,2),
      tact_ayudas_defensivas DECIMAL(4,2),
      tact_ayudas_ofensivas DECIMAL(4,2),
      tact_desmarques DECIMAL(4,2),
      tact_marcajes DECIMAL(4,2),
      phys_sacrificio DECIMAL(4,2),
      phys_velocidad_punta DECIMAL(4,2),
      phys_velocidad_reaccion DECIMAL(4,2),
      phys_fuerza DECIMAL(4,2),
      phys_potencia DECIMAL(4,2),
      phys_resistencia DECIMAL(4,2),
      phys_coordinacion DECIMAL(4,2),
      psych_concentracion DECIMAL(4,2),
      psych_control_emocional DECIMAL(4,2),
      psych_reaccion_errores_arbitrales DECIMAL(4,2),
      pers_liderazgo DECIMAL(4,2),
      pers_disciplina DECIMAL(4,2),
      pers_reaccion_correcciones_companero DECIMAL(4,2),
      pers_reaccion_correcciones_tecnico DECIMAL(4,2),
      recommendation VARCHAR(50),
      info_reliability DECIMAL(4,2),
      created_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (created_by) REFERENCES users(id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
  `;
  await db.query(sql);

  // Intentar añadir nuevas columnas si la tabla ya existía previamente
  const alterStatements = [
    "ALTER TABLE reports ADD COLUMN IF NOT EXISTS tech_cobertura_balon DECIMAL(4,2)",
    "ALTER TABLE reports ADD COLUMN IF NOT EXISTS tech_conduccion DECIMAL(4,2)",
    "ALTER TABLE reports ADD COLUMN IF NOT EXISTS tech_control DECIMAL(4,2)",
    "ALTER TABLE reports ADD COLUMN IF NOT EXISTS tech_regate DECIMAL(4,2)",
    "ALTER TABLE reports ADD COLUMN IF NOT EXISTS tech_disparo DECIMAL(4,2)",
    "ALTER TABLE reports ADD COLUMN IF NOT EXISTS tech_pase DECIMAL(4,2)",
    "ALTER TABLE reports ADD COLUMN IF NOT EXISTS tech_remate_cabeza DECIMAL(4,2)",
    "ALTER TABLE reports ADD COLUMN IF NOT EXISTS tech_anticipacion DECIMAL(4,2)",
    "ALTER TABLE reports ADD COLUMN IF NOT EXISTS tact_transicion_ataque_defensa DECIMAL(4,2)",
    "ALTER TABLE reports ADD COLUMN IF NOT EXISTS tact_movimientos_sin_balon DECIMAL(4,2)",
    "ALTER TABLE reports ADD COLUMN IF NOT EXISTS tact_ayudas_defensivas DECIMAL(4,2)",
    "ALTER TABLE reports ADD COLUMN IF NOT EXISTS tact_ayudas_ofensivas DECIMAL(4,2)",
    "ALTER TABLE reports ADD COLUMN IF NOT EXISTS tact_desmarques DECIMAL(4,2)",
    "ALTER TABLE reports ADD COLUMN IF NOT EXISTS tact_marcajes DECIMAL(4,2)",
    "ALTER TABLE reports ADD COLUMN IF NOT EXISTS phys_sacrificio DECIMAL(4,2)",
    "ALTER TABLE reports ADD COLUMN IF NOT EXISTS phys_velocidad_punta DECIMAL(4,2)",
    "ALTER TABLE reports ADD COLUMN IF NOT EXISTS phys_velocidad_reaccion DECIMAL(4,2)",
    "ALTER TABLE reports ADD COLUMN IF NOT EXISTS phys_fuerza DECIMAL(4,2)",
    "ALTER TABLE reports ADD COLUMN IF NOT EXISTS phys_potencia DECIMAL(4,2)",
    "ALTER TABLE reports ADD COLUMN IF NOT EXISTS phys_resistencia DECIMAL(4,2)",
    "ALTER TABLE reports ADD COLUMN IF NOT EXISTS phys_coordinacion DECIMAL(4,2)",
    "ALTER TABLE reports ADD COLUMN IF NOT EXISTS psych_concentracion DECIMAL(4,2)",
    "ALTER TABLE reports ADD COLUMN IF NOT EXISTS psych_control_emocional DECIMAL(4,2)",
    "ALTER TABLE reports ADD COLUMN IF NOT EXISTS psych_reaccion_errores_arbitrales DECIMAL(4,2)",
    "ALTER TABLE reports ADD COLUMN IF NOT EXISTS pers_liderazgo DECIMAL(4,2)",
    "ALTER TABLE reports ADD COLUMN IF NOT EXISTS pers_disciplina DECIMAL(4,2)",
    "ALTER TABLE reports ADD COLUMN IF NOT EXISTS pers_reaccion_correcciones_companero DECIMAL(4,2)",
    "ALTER TABLE reports ADD COLUMN IF NOT EXISTS pers_reaccion_correcciones_tecnico DECIMAL(4,2)",
  ];

  // eslint-disable-next-line no-restricted-syntax
  for (const stmt of alterStatements) {
    try {
      // eslint-disable-next-line no-await-in-loop
      await db.query(stmt);
    } catch (e) {
      // ignoramos errores si la versión de MySQL no soporta IF NOT EXISTS
    }
  }
}

async function createReport(data) {
  const {
    player_name,
    player_surname,
    year,
    club,
    team,
    laterality,
    contact,
    pos1,
    pos2,
    pos3,
    pos4,
    overall_rating,
    comments,
    tech_total,
    tact_total,
    phys_total,
    psych_total,
    pers_total,
    tech_cobertura_balon,
    tech_conduccion,
    tech_control,
    tech_regate,
    tech_disparo,
    tech_pase,
    tech_remate_cabeza,
    tech_anticipacion,
    tact_transicion_ataque_defensa,
    tact_movimientos_sin_balon,
    tact_ayudas_defensivas,
    tact_ayudas_ofensivas,
    tact_desmarques,
    tact_marcajes,
    phys_sacrificio,
    phys_velocidad_punta,
    phys_velocidad_reaccion,
    phys_fuerza,
    phys_potencia,
    phys_resistencia,
    phys_coordinacion,
    psych_concentracion,
    psych_control_emocional,
    psych_reaccion_errores_arbitrales,
    pers_liderazgo,
    pers_disciplina,
    pers_reaccion_correcciones_companero,
    pers_reaccion_correcciones_tecnico,
    recommendation,
    info_reliability,
    created_by,
  } = data;

  const [result] = await db.query(
    `INSERT INTO reports (
      player_name, player_surname, year, club, team, laterality, contact,
      pos1, pos2, pos3, pos4, overall_rating, comments,
      tech_total, tact_total, phys_total, psych_total, pers_total,
      tech_cobertura_balon, tech_conduccion, tech_control, tech_regate,
      tech_disparo, tech_pase, tech_remate_cabeza, tech_anticipacion,
      tact_transicion_ataque_defensa, tact_movimientos_sin_balon,
      tact_ayudas_defensivas, tact_ayudas_ofensivas, tact_desmarques,
      tact_marcajes,
      phys_sacrificio, phys_velocidad_punta, phys_velocidad_reaccion,
      phys_fuerza, phys_potencia, phys_resistencia, phys_coordinacion,
      psych_concentracion, psych_control_emocional,
      psych_reaccion_errores_arbitrales,
      pers_liderazgo, pers_disciplina,
      pers_reaccion_correcciones_companero,
      pers_reaccion_correcciones_tecnico,
      recommendation, info_reliability, created_by
    ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,
    [
      player_name,
      player_surname,
      year,
      club,
      team,
      laterality,
      contact,
      pos1,
      pos2,
      pos3,
      pos4,
      overall_rating,
      comments,
      tech_total,
      tact_total,
      phys_total,
      psych_total,
      pers_total,
      tech_cobertura_balon,
      tech_conduccion,
      tech_control,
      tech_regate,
      tech_disparo,
      tech_pase,
      tech_remate_cabeza,
      tech_anticipacion,
      tact_transicion_ataque_defensa,
      tact_movimientos_sin_balon,
      tact_ayudas_defensivas,
      tact_ayudas_ofensivas,
      tact_desmarques,
      tact_marcajes,
      phys_sacrificio,
      phys_velocidad_punta,
      phys_velocidad_reaccion,
      phys_fuerza,
      phys_potencia,
      phys_resistencia,
      phys_coordinacion,
      psych_concentracion,
      psych_control_emocional,
      psych_reaccion_errores_arbitrales,
      pers_liderazgo,
      pers_disciplina,
      pers_reaccion_correcciones_companero,
      pers_reaccion_correcciones_tecnico,
      recommendation,
      info_reliability,
      created_by,
    ],
  );
  return result.insertId;
}

module.exports = {
  createReportsTable,
  createReport,
};
